### ISSUE TITLE
Stuck in a loop without learning progress?

### ISSUE THREAD

**Issue by clstaudt** [raoulvm/reinforcement_mars_lander#5]
With the lastest version `b31cdc8c5718e3daf7789eb7021612bf0a428ba3` I cannot observe training progress anymore. The skycrane seems stuck in a loop where it rotates into the tether in the first seconds. Then the simulation restarts. Average rewards stagnates around -365 after ca. 500 episodes.

**Comment by raoulvm** [comment]
Sounds strange in such a late phase of learning. However, as you can see here in episodes 350 to 400
![reward curve training](https://github.com/raoulvm/reinforcement_mars_lander/blob/main/Figure%201-%20Reward%20for%20each%20training%20episode.png?raw=true)
it seems perfectly normal that the network learns a strange behavior and takes several episodes to "unlearn" it again.  
Especially the "strange rotation behavior" occurred several times during my training as well, therefore I introduced a "game over" if the angle of either vessel is beyond pi/2.

**Comment by clstaudt** [comment]
Okay, seems like randomized and rare behavior. Can't reproduce it anymore.
